// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DIRECT_URL"]!,
  },
});

// we use direct url for none pooled stuff/ seeding migration and pooled url for the app itself, this is because of the connection limit of neon and the fact that prisma adapter neon does not support pooling yet, so we use the direct url for seeding and migrations and the pooled url for the app itself.
