import type { Metadata } from "next";
import { Inter, Geist } from "next/font/google";
import "../assets/styles/globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${geist.variable} antialiased `} //or InterSans.className if you don't want to use CSS variables
      >
        {children}
      </body>
    </html>
  );
}
