import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "../assets/styles/globals.css";

const InterSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${InterSans.variable} antialiased `} //or InterSans.className if you don't want to use CSS variables
      >
        {children}
      </body>
    </html>
  );
}
