const sampleData = {
   products : [
  {
    name: 'Polo Sporting Stretch Shirt',
    nameAr: 'قميص بولو سبورتينج سترتش',
    slug: 'polo-sporting-stretch-shirt',
    category: "Men's Dress Shirts",
    categoryAr: 'قمصان رسمية رجالية',
    description: 'Classic Polo style with modern comfort',
    descriptionAr: 'ستايل بولو الكلاسيكي مع راحة عصرية',
    images: [
      '/images/sample-products/p1-1.jpg',
      '/images/sample-products/p1-2.jpg',
    ],
    price: 59.99,
    brand: 'Polo',
    brandAr: 'بولو',
    rating: 4.5,
    numReviews: 10,
    stock: 5,
    isFeatured: true,
    banner: 'banner-1.jpg',
  },
  {
    name: 'Brooks Brothers Long Sleeved Shirt',
    nameAr: 'قميص بروكس براذرز بأكمام طويلة',
    slug: 'brooks-brothers-long-sleeved-shirt',
    category: "Men's Dress Shirts",
    categoryAr: 'قمصان رسمية رجالية',
    description: 'Timeless style and premium comfort',
    descriptionAr: 'أناقة خالدة وراحة فائقة',
    images: [
      '/images/sample-products/p2-1.jpg',
      '/images/sample-products/p2-2.jpg',
    ],
    price: 85.9,
    brand: 'Brooks Brothers',
    brandAr: 'بروكس براذرز',
    rating: 4.2,
    numReviews: 8,
    stock: 10,
    isFeatured: true,
    banner: 'banner-2.jpg',
  },
  {
    name: 'Tommy Hilfiger Classic Fit Dress Shirt',
    nameAr: 'قميص تومي هيلفيغر كلاسيك فيت',
    slug: 'tommy-hilfiger-classic-fit-dress-shirt',
    category: "Men's Dress Shirts",
    categoryAr: 'قمصان رسمية رجالية',
    description: 'A perfect blend of sophistication and comfort',
    descriptionAr: 'مزيج مثالي بين الرقي والراحة',
    images: [
      '/images/sample-products/p3-1.jpg',
      '/images/sample-products/p3-2.jpg',
    ],
    price: 99.95,
    brand: 'Tommy Hilfiger',
    brandAr: 'تومي هيلفيغر',
    rating: 4.9,
    numReviews: 3,
    stock: 0,
    isFeatured: false,
    banner: null,
  },
  {
    name: 'Calvin Klein Slim Fit Stretch Shirt',
    nameAr: 'قميص كالفن كلاين سليم فيت سترتش',
    slug: 'calvin-klein-slim-fit-stretch-shirt',
    category: "Men's Dress Shirts",
    categoryAr: 'قمصان رسمية رجالية',
    description: 'Streamlined design with flexible stretch fabric',
    descriptionAr: 'تصميم انسيابي مع نسيج مرن ومريح',
    images: [
      '/images/sample-products/p4-1.jpg',
      '/images/sample-products/p4-2.jpg',
    ],
    price: 39.95,
    brand: 'Calvin Klein',
    brandAr: 'كالفن كلاين',
    rating: 3.6,
    numReviews: 5,
    stock: 10,
    isFeatured: false,
    banner: null,
  },
  {
    name: 'Polo Ralph Lauren Oxford Shirt',
    nameAr: 'قميص بولو رالف لورين أكسفورد',
    slug: 'polo-ralph-lauren-oxford-shirt',
    category: "Men's Dress Shirts",
    categoryAr: 'قمصان رسمية رجالية',
    description: 'Iconic Polo design with refined oxford fabric',
    descriptionAr: 'تصميم بولو الشهير بنسيج أكسفورد الراقي',
    images: [
      '/images/sample-products/p5-1.jpg',
      '/images/sample-products/p5-2.jpg',
    ],
    price: 79.99,
    brand: 'Polo',
    brandAr: 'بولو',
    rating: 4.7,
    numReviews: 18,
    stock: 6,
    isFeatured: false,
    banner: null,
  },
  {
    name: 'Polo Classic Pink Hoodie',
    nameAr: 'هودي بولو كلاسيك وردي',
    slug: 'polo-classic-pink-hoodie',
    category: "Men's Sweatshirts",
    categoryAr: 'سويت شيرت رجالي',
    description: 'Soft, stylish, and perfect for laid-back days',
    descriptionAr: 'ناعم، أنيق، ومثالي للأيام المريحة',
    images: [
      '/images/sample-products/p6-1.jpg',
      '/images/sample-products/p6-2.jpg',
    ],
    price: 99.99,
    brand: 'Polo',
    brandAr: 'بولو',
    rating: 4.6,
    numReviews: 12,
    stock: 8,
    isFeatured: true,
    banner: null,
  },
],
};

export default sampleData;
